name: test

on:
  workflow_dispatch:
    inputs:
      addon_version:
        type: string
        description: "Addon version without 'v' prefix."
        required: true
  release:
    types:
      - created

env:
  addon_version: ${{ inputs.addon_version | github.ref_name }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo $addon_version