name: test

on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - run: aws help
#      - uses: actions/checkout@v2
#      - uses: ./test
#        with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
